-- AlterEnum
ALTER TYPE "Role" ADD VALUE 'PRIMEIRO_DIACONO';
ALTER TYPE "Role" ADD VALUE 'SEGUNDO_DIACONO';
ALTER TYPE "Role" ADD VALUE 'ORADOR';
ALTER TYPE "Role" ADD VALUE 'GUARDA_INTERNO';
ALTER TYPE "Role" ADD VALUE 'GUARDA_EXTERNO';
ALTER TYPE "Role" ADD VALUE 'DIRETOR_CERIMONIAS';
